export interface LocalSupplier {
  id: string;
  name: string;
  category: 'produce' | 'meat' | 'seafood' | 'dairy' | 'bakery' | 'beverage' | 'equipment' | 'specialty';
  categoryLabel: string;
  specialty: string;
  address: string;
  city: string;
  region: string;
  mapsUri: string;
  phone?: string;
  email?: string;
  website?: string;
  rating?: number;
  reviewCount?: number;
  deliveryAvailable: boolean;
  minOrder?: string;
  orderCutoff?: string;
  haccpCertified: boolean;
  chefNotes: string;
  popularItems: string[];
}

export const VERIFIED_LOCAL_SUPPLIERS: LocalSupplier[] = [
  // --- CAPE TOWN & WESTERN CAPE ---
  {
    id: 'epping-market',
    name: 'Cape Town Market (Epping Fresh Produce)',
    category: 'produce',
    categoryLabel: 'Fresh Produce & Farming',
    specialty: 'Bulk seasonal fruit, organic vegetables, and micro-herbs direct from Western Cape farms',
    address: '110 Gunners Circle, Epping 1, Cape Town',
    city: 'Cape Town',
    region: 'Western Cape',
    mapsUri: 'https://maps.google.com/?cid=12592398450123981023&q=Cape+Town+Market+Epping',
    phone: '+27 21 531 2191',
    website: 'https://www.capetownmarket.co.za',
    rating: 4.6,
    reviewCount: 420,
    deliveryAvailable: true,
    minOrder: 'R 1,500',
    orderCutoff: '15:00 for Next-Day 06:00 Delivery',
    haccpCertified: true,
    chefNotes: 'The premier primary wholesale produce hub for hotel banquets. Excellent early-morning auction lots.',
    popularItems: ['Baby Heritage Carrots', 'Romanesco Cauliflower', 'Cape Strawberries', 'Micro Rocket', 'Heirloom Vine Tomatoes']
  },
  {
    id: 'frankie-fenner',
    name: 'Frankie Fenner Meat Merchants (FFMM)',
    category: 'meat',
    categoryLabel: 'Wholesale Butchery & Meats',
    specialty: 'Pasture-reared, ethically raised Karoo lamb, grass-fed beef, and bespoke charcuterie cuts',
    address: '81 Church St, Cape Town City Centre',
    city: 'Cape Town',
    region: 'Western Cape',
    mapsUri: 'https://maps.google.com/?q=Frankie+Fenner+Meat+Merchants+Cape+Town',
    phone: '+27 21 424 7204',
    website: 'https://ffmm.co.za',
    rating: 4.8,
    reviewCount: 310,
    deliveryAvailable: true,
    minOrder: 'R 2,000',
    orderCutoff: '12:00 for Next-Day Delivery',
    haccpCertified: true,
    chefNotes: 'Crucial for upscale plated banquets and VIP functions. Prime dry-aged ribeye and certified Karoo lamb saddles.',
    popularItems: ['Karoo Lamb Racks', 'Dry-Aged Beef Fillet', 'Free-Range Pork Belly', 'Artisanal Biltong', 'Duck Breast']
  },
  {
    id: 'ocean-jewels-greenfish',
    name: 'Greenfish Wholesale & Ocean Catch',
    category: 'seafood',
    categoryLabel: 'Ocean & Coastal Seafood',
    specialty: 'SASI-green listed fresh linefish, West Coast rock lobster, Franschhoek trout, and Saldanha oysters',
    address: 'Paarden Eiland Industrial, Cape Town',
    city: 'Cape Town',
    region: 'Western Cape',
    mapsUri: 'https://maps.google.com/?q=Greenfish+Wholesale+Paarden+Eiland',
    phone: '+27 21 510 1450',
    website: 'https://greenfish.co.za',
    rating: 4.9,
    reviewCount: 280,
    deliveryAvailable: true,
    minOrder: 'R 1,200',
    orderCutoff: '14:00 (Delivered on wet-ice by 08:00)',
    haccpCertified: true,
    chefNotes: 'Strict cold-chain transit on slurry ice. Invaluable for same-day harvest linefish and gala shellfish displays.',
    popularItems: ['Cape Linefish (Yellowtail / Cape Salmon)', 'Saldanha Bay Oysters', 'Franschhoek Cold-Smoked Trout', 'King Scallops']
  },
  {
    id: 'dalewood-fairview',
    name: 'Fairview Farm & Dalewood Fromage',
    category: 'dairy',
    categoryLabel: 'Artisan Dairy & Cheese',
    specialty: 'Estate Jersey milk Brie, Camembert, goat chevin, cultured cream, and farmhouse butter',
    address: 'Klapmuts-Simondium Rd, Paarl / Franschhoek',
    city: 'Paarl / Franschhoek',
    region: 'Western Cape',
    mapsUri: 'https://maps.google.com/?q=Fairview+Cheese+Paarl',
    phone: '+27 21 863 2450',
    website: 'https://www.fairview.co.za',
    rating: 4.7,
    reviewCount: 512,
    deliveryAvailable: true,
    minOrder: 'R 800',
    orderCutoff: '48h Lead Time for Aged Wheels',
    haccpCertified: true,
    chefNotes: 'Benchmark cheese supplier for grazing tables, wedding cheese towers, and Escoffier pastry sauces.',
    popularItems: ['Estate Camembert', 'Whipped Goat Chevin', 'Aged Blue Rock', 'Cultured Farmhouse Butter', 'Double Cream Brie']
  },
  {
    id: 'wild-peacock',
    name: 'Wild Peacock Food Emporium',
    category: 'specialty',
    categoryLabel: 'Specialty & Gourmet Importers',
    specialty: 'Valrhona chocolates, French duck confit, truffles, caviar, artisan vinegars, and micro-delicacies',
    address: 'Plankenbrug Industrial, Stellenbosch',
    city: 'Stellenbosch',
    region: 'Western Cape',
    mapsUri: 'https://maps.google.com/?q=Wild+Peacock+Food+Emporium+Stellenbosch',
    phone: '+27 21 801 3663',
    website: 'https://wildpeacock.co.za',
    rating: 4.8,
    reviewCount: 195,
    deliveryAvailable: true,
    minOrder: 'R 1,500',
    orderCutoff: '13:00 for Cape Town Delivery',
    haccpCertified: true,
    chefNotes: 'The go-to purveyor for pastry chefs, micro-herbs, molecular textures, and imported French delicacies.',
    popularItems: ['Valrhona 70% Dark Chocolate', 'Winter Black Truffles', 'Duck Confit Legs', 'Artisanal Extra Virgin Olive Oil']
  },
  {
    id: 'eureka-mills',
    name: 'Eureka Mills Stoneground Flour Depot',
    category: 'bakery',
    categoryLabel: 'Flour, Bakery & Pastry Supplies',
    specialty: 'Unbleached stoneground flours, sourdough starters, rye meal, and artisan baking ingredients',
    address: 'Heidelberg & Epping Depot, Cape Town',
    city: 'Cape Town',
    region: 'Western Cape',
    mapsUri: 'https://maps.google.com/?q=Eureka+Mills+Cape+Town',
    phone: '+27 28 722 1887',
    website: 'https://eurekamills.co.za',
    rating: 4.7,
    reviewCount: 160,
    deliveryAvailable: true,
    minOrder: '50kg Bulk Bags',
    orderCutoff: '24h Notice',
    haccpCertified: true,
    chefNotes: 'Superior stoneground wheat without chemical enhancers. Perfect crumb structure for banquet bread baskets.',
    popularItems: ['Stoneground White Bread Flour', 'Rye Flour', 'Wholewheat Coarse Meal', 'Ciabatta Premix']
  },
  {
    id: 'bidfood-western-cape',
    name: 'Bidfood Western Cape (Foodservice)',
    category: 'equipment',
    categoryLabel: 'Commercial Foodservice & Provisions',
    specialty: 'Full-line hotel kitchen distributor: dry goods, packaging, frozen seafood, oils, and hygiene chemicals',
    address: '1 Manhattan St, Airport Industria, Cape Town',
    city: 'Cape Town',
    region: 'Western Cape',
    mapsUri: 'https://maps.google.com/?q=Bidfood+Western+Cape+Airport+Industria',
    phone: '+27 21 927 2000',
    website: 'https://www.bidfood.co.za',
    rating: 4.4,
    reviewCount: 380,
    deliveryAvailable: true,
    minOrder: 'R 3,000',
    orderCutoff: '16:00 Daily for Scheduled Route Delivery',
    haccpCertified: true,
    chefNotes: 'Essential for high-volume banqueting dry provisions, cooking oils, dairy, and catering disposables.',
    popularItems: ['Canola Cooking Oil (20L)', 'Catering Grade Butter 25kg', 'Bio-Degradable Cloche Boxes', 'Sanitizer 25L']
  },

  // --- JOHANNESBURG & GAUTENG ---
  {
    id: 'joburg-market-city-deep',
    name: 'Joburg Market (City Deep Wholesale Produce)',
    category: 'produce',
    categoryLabel: 'Fresh Produce & Farming',
    specialty: 'The largest fresh produce market in Africa. Over 1,500 tonnes of fresh fruits and vegetables daily',
    address: '4 Fortune St, City Deep, Johannesburg',
    city: 'Johannesburg',
    region: 'Gauteng',
    mapsUri: 'https://maps.google.com/?q=Joburg+Market+City+Deep+Johannesburg',
    phone: '+27 11 992 8000',
    website: 'https://joburgmarket.co.za',
    rating: 4.5,
    reviewCount: 890,
    deliveryAvailable: true,
    minOrder: 'Bulk Pallets / Wholesale crates',
    orderCutoff: 'Trade opens at 05:00 AM',
    haccpCertified: true,
    chefNotes: 'Direct trade floor with wholesale commission agents. Unbeatable wholesale prices for 100+ cover hotel operations.',
    popularItems: ['Potatoes Grade 1 (10kg)', 'Brown Onions', 'Hydroponic Salad Leaves', 'Export Avocados', 'Citrus Crates']
  },
  {
    id: 'braeside-meat-co',
    name: 'Braeside Butchery & Wholesale Meat Co.',
    category: 'meat',
    categoryLabel: 'Wholesale Butchery & Meats',
    specialty: 'Ethical grass-fed beef, free-range poultry, artisan boerewors, and dry-aged steaks',
    address: '4th Ave, Parkhurst / Kya Sand Depot, Johannesburg',
    city: 'Johannesburg',
    region: 'Gauteng',
    mapsUri: 'https://maps.google.com/?q=Braeside+Butchery+Johannesburg',
    phone: '+27 11 788 3613',
    website: 'https://braesidebutchery.co.za',
    rating: 4.8,
    reviewCount: 340,
    deliveryAvailable: true,
    minOrder: 'R 2,500',
    orderCutoff: '13:00 for Gauteng Route Delivery',
    haccpCertified: true,
    chefNotes: 'Antibiotic-free, hormone-free beef and lamb. High yield consistency with minimal trimming waste.',
    popularItems: ['Dry-Aged T-Bone Steaks', 'Pasture-Fed Beef Fillet', 'Champion Artisan Boerewors', 'Free-Range Chicken Breast']
  },
  {
    id: 'southern-cross-seafoods',
    name: 'Southern Cross Seafood Wholesalers',
    category: 'seafood',
    categoryLabel: 'Ocean & Coastal Seafood',
    specialty: 'Air-freighted coastal linefish, Norwegian salmon sides, prawns, calamari, and shellfish',
    address: 'Heidelberg Rd, City Deep Industrial, Johannesburg',
    city: 'Johannesburg',
    region: 'Gauteng',
    mapsUri: 'https://maps.google.com/?q=Southern+Cross+Seafood+City+Deep',
    phone: '+27 11 613 6711',
    website: 'https://southerncrossseafood.co.za',
    rating: 4.6,
    reviewCount: 215,
    deliveryAvailable: true,
    minOrder: 'R 2,000',
    orderCutoff: '12:00 for Next-Day Delivery',
    haccpCertified: true,
    chefNotes: 'Daily air-freight deliveries from Cape Town and Durban harbors. Guaranteed unbroken cold chain.',
    popularItems: ['Fresh Atlantic Salmon Sides', 'Queen Tiger Prawns (Headless)', 'Patagonian Calamari Tubes', 'Kingklip Fillets']
  },
  {
    id: 'continental-delicacies-jhb',
    name: 'Continental Delicacies & Mediterranean Gourmet',
    category: 'specialty',
    categoryLabel: 'Specialty & Gourmet Importers',
    specialty: 'Imported Italian prosciutto di Parma, aged Parmigiano Reggiano, truffle oils, and Belgian baking couverture',
    address: 'Meadowdale / Germiston, Johannesburg',
    city: 'Johannesburg',
    region: 'Gauteng',
    mapsUri: 'https://maps.google.com/?q=Continental+Delicacies+Gauteng',
    phone: '+27 11 453 1120',
    website: 'https://continentaldelicacies.co.za',
    rating: 4.7,
    reviewCount: 178,
    deliveryAvailable: true,
    minOrder: 'R 1,500',
    orderCutoff: '14:00 Daily',
    haccpCertified: true,
    chefNotes: 'Essential wholesale partner for classical banquet banquets, Italian antipasti, and Escoffier stocks.',
    popularItems: ['Parmigiano Reggiano 24-Month', 'San Daniele Prosciutto', 'White Truffle Butter', 'Arborio Risotto Rice']
  },

  // --- DURBAN & KWAZULU-NATAL ---
  {
    id: 'clairwood-bulk-market',
    name: 'Durban Wholesale Fresh Produce Market',
    category: 'produce',
    categoryLabel: 'Fresh Produce & Farming',
    specialty: 'Tropical subtropical produce, Natal coastal herbs, pineapples, mangos, and Asian greens',
    address: 'Flower Rd, Clairwood, Durban',
    city: 'Durban',
    region: 'KwaZulu-Natal',
    mapsUri: 'https://maps.google.com/?q=Durban+Fresh+Produce+Market+Clairwood',
    phone: '+27 31 465 5565',
    website: 'https://durbanmarket.co.za',
    rating: 4.4,
    reviewCount: 310,
    deliveryAvailable: true,
    minOrder: 'Wholesale crates',
    orderCutoff: '06:00 AM Morning Market',
    haccpCertified: true,
    chefNotes: 'Finest source for exotic tropical fruits, curry spices, dhania, and coastal vegetables in KZN.',
    popularItems: ['Sugarloaf Pineapples', 'Natal Mango Crates', 'Fresh Coriander / Dhania', 'Baby Gem Squash', 'Curry Leaves']
  },
  {
    id: 'barthos-fish-durban',
    name: "Bartho's Fish Co. & Ocean Harvest",
    category: 'seafood',
    categoryLabel: 'Ocean & Coastal Seafood',
    specialty: 'Day-boat caught Indian Ocean linefish, dorado, tuna, swordfish, and coastal crabs',
    address: 'Mackeurtan Ave, Durban North',
    city: 'Durban',
    region: 'KwaZulu-Natal',
    mapsUri: 'https://maps.google.com/?q=Barthos+Fish+Co+Durban+North',
    phone: '+27 31 563 4304',
    website: 'https://barthosfish.co.za',
    rating: 4.9,
    reviewCount: 260,
    deliveryAvailable: true,
    minOrder: 'R 1,000',
    orderCutoff: '11:00 for Afternoon Coastal Drop',
    haccpCertified: true,
    chefNotes: 'Direct relations with local ski-boat fishermen. Freshest yellowfin tuna and dorado available in KZN.',
    popularItems: ['Yellowfin Tuna Loins', 'Wild Dorado Fillets', 'Mozambican Prawns', 'Red Roman / Slinger']
  },

  // --- LIMPOPO & MOKOPANE / WATERBERG HUB ---
  {
    id: 'mokopane-meat-market',
    name: "Uncle Joe's Meat Market & Bushveld Butchery",
    category: 'meat',
    categoryLabel: 'Wholesale Butchery & Meats',
    specialty: 'A-Grade regional lamb mince, Bushveld prime beef cuts, venison game steaks, and signature spiced boerewors',
    address: 'Thabo Mbeki Dr, Mokopane (Potgietersrus), Limpopo',
    city: 'Mokopane',
    region: 'Limpopo',
    mapsUri: 'https://maps.google.com/?q=Meat+Market+Mokopane+Limpopo',
    phone: '+27 15 491 3240',
    website: 'https://unclejoesmeat.co.za',
    rating: 4.8,
    reviewCount: 195,
    deliveryAvailable: true,
    minOrder: 'R 850',
    orderCutoff: '14:00 Daily for Lodge & Venue Drop',
    haccpCertified: true,
    chefNotes: 'Unbeatable regional lamb mince @ R110/kg and prime beef cuts. Reliable cold-truck service throughout Waterberg & Polokwane.',
    popularItems: ['Lamb Mince (R110/kg)', 'Bushveld Beef Fillet', 'Farmhouse Boerewors', 'Springbok Loin', 'Pork Belly Rashers']
  },
  {
    id: 'polokwane-fresh-produce-market',
    name: 'Polokwane Wholesale Fresh Produce Market',
    category: 'produce',
    categoryLabel: 'Fresh Produce & Farming',
    specialty: 'Limpopo citrus, subtropical avocados, waterberg potatoes, onions, butternut, and fresh culinary herbs',
    address: 'Silicon Rd, Polokwane Industrial, Limpopo',
    city: 'Polokwane / Mokopane',
    region: 'Limpopo',
    mapsUri: 'https://maps.google.com/?q=Polokwane+Fresh+Produce+Market',
    phone: '+27 15 293 1222',
    rating: 4.5,
    reviewCount: 220,
    deliveryAvailable: true,
    minOrder: 'Wholesale crates',
    orderCutoff: '05:30 AM Trade Floor Open',
    haccpCertified: true,
    chefNotes: 'Direct farmer supply network spanning the Limpopo agricultural basin. Fresh farm-gate pricing on all bulk vegetables.',
    popularItems: ['Limpopo Hass Avocados', 'Waterberg Potatoes (10kg)', 'Fresh Coriander & Basil', 'Citrus Crates', 'Sweet Butternut']
  },
  {
    id: 'waterberg-dairy-limpopo',
    name: 'Waterberg Farmhouse Dairy & Fromagerie',
    category: 'dairy',
    categoryLabel: 'Artisan Dairy & Cheese',
    specialty: 'Farm fresh whole milk, cultured salted butter, gouda, cheddar blocks, and whipping cream for catering passes',
    address: 'R101 Farm Route, Mokopane / Bela-Bela',
    city: 'Mokopane',
    region: 'Limpopo',
    mapsUri: 'https://maps.google.com/?q=Waterberg+Dairy+Limpopo',
    phone: '+27 15 491 8840',
    rating: 4.7,
    reviewCount: 88,
    deliveryAvailable: true,
    minOrder: 'R 600',
    orderCutoff: '12:00 for Next-Day Chilled Delivery',
    haccpCertified: true,
    chefNotes: 'Farm-fresh pasture dairy. Thick double cream and salted farmhouse butter perfect for banquet sauces and pastry baking.',
    popularItems: ['Farmhouse Salted Butter', 'Double Whipping Cream (5L)', 'Mild Gouda Wheel', 'Full Cream Milk (20L Urn)']
  }
];
