# ==============================================================================
#  🚀 FORCE DEPLOY WORKFLOW
# ==============================================================================

name: '🚀 Force Deploy to Firebase'

on:
  push:
    branches:
      - 'main'
      - 'master'
  workflow_dispatch: # Allows you to click "Run workflow" manually in the Actions tab

# Prevent multiple instances of this workflow from running simultaneously
concurrency:
  group: 'firebase-deployment'
  cancel-in-progress: true

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: 'Step 1: Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Step 2: Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 'Step 3: Install Dependencies'
        run: npm ci

      - name: 'Step 4: Build App'
        run: npm run build

      - name: 'Step 5: Deploy to Firebase'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: 'caterpro-ai'
          channelId: live
