import React from 'react';

/**
 * Defines the structure for a delivery fee calculation model.
 */
export interface DeliveryFeeStructure {
  baseFee: number;
  perUnitRate: number;
  unit: 'mile' | 'km';
  currency: string;
}

/**
 * The main interface for a complete menu proposal generated by the AI.
 */
export interface Menu {
  menuTitle: string;
  description: string;
  appetizers: string[];
  mainCourses: string[];
  sideDishes: string[];
  dessert: string[];
  beveragePairings: BeveragePairing[];
  miseEnPlace: string[];
  serviceNotes: string[];
  deliveryLogistics: string[];
  shoppingList: ShoppingListItem[];
  recommendedEquipment: RecommendedEquipment[];
  /**
   * Notes explaining how dietary restrictions were handled.
   */
  dietaryNotes?: string[];
  /**
   * Base64 encoded string of the generated menu image.
   */
  image?: string;
  /**
   * Sourcing information from Google Search or Maps.
   */
  groundingChunks?: GroundingChunk[];
  /**
   * The visual theme identifier for the proposal.
   */
  theme?: string;
  /**
   * A structured object for calculating delivery fees.
   */
  deliveryFeeStructure?: DeliveryFeeStructure;
}

/**
 * Represents a suggested beverage pairing for a menu item.
 */
export interface BeveragePairing {
  menuItem: string;
  pairingSuggestion: string;
}

/**
 * Represents a single item in the shopping list.
 */
export interface ShoppingListItem {
  store: string;
  category: string;
  item: string;
  quantity: string;
  /**
   * An enticing description for specialty items, used for affiliate marketing.
   */
  description?: string;
  /**
   * A search term for specialty items, optimized for affiliate links.
   */
  affiliateSearchTerm?: string;
  /**
   * An estimated cost range for the item, in the local currency.
   */
  estimatedCost?: string;
  /**
   * Specific brand suggestions for the item.
   */
  brandSuggestion?: string;
}

/**
 * Represents a piece of recommended equipment or supply.
 */
export interface RecommendedEquipment {
  item: string;
  description: string;
}

/**
 * Represents a grounding chunk from the Gemini API, containing web or map sources.
 */
export interface GroundingChunk {
  maps?: {
    uri?: string;
    title?: string;
  };
  web?: {
    uri?: string;
    title?: string;
  };
}

/**
 * Represents a menu that has been saved by the user.
 */
export interface SavedMenu {
  id: number;
  title: string;
  content: Menu;
  savedAt: string;
}

/**
 * Represents a product.
 * @note This type is for product-related components that may not be fully integrated.
 */
export interface PpeProduct {
  id: number;
  name: string;
  description: string;
  image: string;
  priceRange: '$' | '$$' | '$$$';
}

/**
 * Defines the structure for displaying error messages to the user.
 */
export interface ErrorState {
  title: string;
  message: string | React.ReactNode;
}

/**
 * Defines the structure for form validation errors.
 */
export interface ValidationErrors {
  eventType?: string;
  guestCount?: string;
  cuisine?: string;
}

/**
 * Defines the structure for a chat message in the AI assistant.
 */
export interface Message {
  role: 'user' | 'model';
  content: string;
}

/**
 * Defines the structure for an item in the generation history.
 */
export interface GenerationHistoryItem {
  id: number;
  eventType: string;
  guestCount: string;
  cuisine: string;
  serviceStyle: string;
  dietaryRestrictions: string[];
  timestamp: string;
}

/**
 * A union type representing all the sections within a menu proposal.
 */
export type MenuSection =
  | 'appetizers'
  | 'mainCourses'
  | 'sideDishes'
  | 'dessert'
  | 'beveragePairings'
  | 'miseEnPlace'
  | 'serviceNotes'
  | 'deliveryLogistics'
  | 'shoppingList'
  | 'recommendedEquipment'
  | 'dietaryNotes';

/**
 * Represents a supplier or catering service found via Google Maps.
 */
export interface Supplier {
  name: string;
  specialty: string;
  mapsUri?: string;
  title?: string;
}
